resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: git
      path: batelt/devops-101-workshop
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: SampleApp
      buildNumber: 1          
pipelines:  
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
          outputResources:
            - name: myBuildInfo             
        execution:
          onExecute:
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$(bump_semver $app_version minor); fi
            - write_output myBuildInfo "buildNumber=$app_version"
            - add_run_variables run_var="hello"

      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: myBuildInfo
            - name: myGitRepo            
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: ['11']
        execution:
          onExecute:
            - cd $res_myGitRepo_resourcePath
            - pwd
            - cd sample-projects/python-example
            - apt-get update && apt-get install python3-pip
            - pip3 install pytest
            - pytest -v

      - name: step_3
        type: Bash
        configuration:
          environmentVariables:
            step_env_var1: "Hello, I am an environment variable declared inside of a step"
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo $step_env_var1

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo $app_version

      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
            - name: step_4  
          integrations:
            - name: git            
        execution:
          onExecute:
            - 'curl -H "Authorization: token ${int_git_token}" ${int_git_url}/rate_limit'
